In [2]:

import pandas as pd

from sklearn.datasets import fetch_openml
mnist=fetch_openml('mnist_784', version=1)

#import numpy as np


C:\Users\damia\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\datasets\_openml.py:932: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [3]:
import numpy as np
#print((np.array(mnist.data.loc[56005]).reshape(28,28)>0).astype(int))
pass

In [4]:
X, y = mnist["data"], mnist["target"].astype(np.uint8)

In [5]:
type(X)

pandas.core.frame.DataFrame

In [6]:
print(type(mnist))
mnist.keys()

<class 'sklearn.utils._bunch.Bunch'>


dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])

In [37]:
X_train, X_test=X[:56000], X[56000:]
y_train, y_test=y[:56000], y[56000:]


In [38]:
y_train_0=(y_train==0)
y_test_0=(y_test==0)

In [39]:
print(y_train_0)
print(np.unique(y_train_0))
print(len(y_train_0))

0        False
1         True
2        False
3        False
4        False
         ...  
55995    False
55996    False
55997    False
55998    False
55999    False
Name: class, Length: 56000, dtype: bool
[False  True]
56000


In [40]:
from           sklearn.linear_model           import           SGDClassifier

sgd_clf=SGDClassifier(random_state=42)
sgd_clf.fit(X_train, y_train_0)

SGDClassifier(random_state=42)

In [41]:
xp=sgd_clf.predict(X_train)
a=0
b=0

for i in range(0, 56000):
    b+=1
    if y_train_0[i]==xp[i]:
        a+=1

print (a/b, "  ", b)

list=[]
list.append(a/b)




xp=sgd_clf.predict(X_test)
a=0
b=0

for i in range(56000, 70000):
    b+=1
    if y_test_0[i]==xp[i-56000]:
        a+=1

print (a/b)
print (b)

list.append(a/b)









0.9901964285714285    56000
0.9877857142857143
14000


In [42]:
# a=0;
# xp=sgd_clf.predict(X_test)[i-56000 :]
# for i in range(56000, 70000):
#     if y_test_0[i]!=xp[i-56000]:
#         a+=1

# print(a)

In [43]:
from numpy import ndarray
from           sklearn.model_selection           import           cross_val_score
import time
start=time.time()
score = ndarray((3, ), buffer=cross_val_score(sgd_clf, X_train, y_train_0, cv=3, scoring="accuracy", n_jobs=-1))

print(time.time()-start)
print(score)


10.619124174118042
[0.98650024 0.98950019 0.98542805]


In [44]:
import pickle as pi

with open('sgd_cva.pkl', 'wb') as f:
    pi.dump(score, f)


In [45]:
with open('sgd_acc.pkl', 'wb') as f:
    pi.dump(list, f)


In [46]:
# from sklearn.svm import SVC
# svm_clf=SVC()
# svm_clf.fit(X_train, y_train)

In [47]:
#xpp=svm_clf.predict(X_test)

# for i in range(56000, 70000):
#     print(y_test[i],  "  ", xpp[i-56000])

In [48]:
sgd_m_clf=SGDClassifier(random_state=42, n_jobs=-1)
sgd_m_clf.fit(X_train, y_train)


SGDClassifier(n_jobs=-1, random_state=42)

In [49]:
# xpp=sgd_m_clf.predict(X_test)
#
# for i in range(56000, 70000):
#     print(y_test[i],  "  ", xpp[i-56000])

In [50]:
y_test_pred=cross_val_score(sgd_m_clf, X_test, y_test, cv=3, n_jobs=-1)


In [51]:
from sklearn.metrics import confusion_matrix

y_test_predict=sgd_m_clf.predict(X_test)
conf_mx=confusion_matrix(y_test, y_test_predict)
print(conf_mx)

[[1345    0    2    7    3    5    4    0    3    4]
 [   0 1521   12    7    0    4    2    0   21    2]
 [  12    6 1333   15   11    2    5    8   34    4]
 [   7    5   98 1181    4   32    4   11   35   36]
 [  10    5   13    4 1269    1    5    3    7   59]
 [  21    5   19   65   33  965   17    3  102   23]
 [  22    1   30    8    5   17 1233    0   23    0]
 [  11    5   34   13   38    6    1 1194    2  179]
 [  20   26   33   49   18   36    6    3 1109   65]
 [  12    9    2   16   54    7    0   14   13 1272]]


In [52]:
with open("sgd_cmx.pkl", "wb") as f:
    pi.dump(conf_mx, f)

In [ ]:
print("xD")